language: node_js
node_js:
  - "node"
cache: npm
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "Co5UsTA7uBfXlex4gpUUQQLBsEvjd6JLWX9HCLiNQlGqRpFxSlJ15LGBqmVBkGabG+aM2wVwBc6VAobyZKiDAHQa6vHN95jv3lYeHgrtspoenB/Wq7yiXTmIzG0pbQwN99yc6cmcLfZjxNe6BW7l8kdb5unhFq3ILBlKWU8qbDgBVNtwbBZGys077yYBPgeSlCLvJZtOMhwkW0k0uTAh40ERJDfiEx7Yy8k63PVwB3WmyWoPnNiF25Z03VDm6xfOJz8mXTWUajUCso6NS10c0zF93iXlf/OKCHmc5M66q6pmYMb37djHXxD9jrJBaeFIKoXaIC3Jt5iROMAiFfB0eSSC3UFMNNJpAGyKPBMoTMensFJyTFTgmKOnpK3d5j/nyF8xjFG/rpZnhBX1BxQd8eniiytL+NaQvx4y2LKe9znL0UTRFTlaqmuVm+66RI7GW2emkTPADtEX1PbU5P+StSFYlp6mvup/hpPmN6dZche8X0s23YBjVgufuUcUGs3wa/QHDYStarMa12W1iRjnF6O0jSsmZnD3Wsf6W750wxqDat1vd9+caEmItaZlXM9bRf4ippNGUmGBj36aczWfqmmkiDPuy4IBk7KEV02Zspcp/IIx02tRvopxCFN2Pue8VagoHp1Zf9d2mkKc8DlOEdTU+8wAGmqwB/I1lBtB2do="
  message: "Automatic deployment by travis - CI"
